### ISSUE TITLE
IsPlayerInArea bounds

### ISSUE THREAD

**Issue by Y-Less** [iPollo/PawnAlgorithms#2]
The upper and lower bounds of this function should not both be inclusive.  With that you can end up marked as in 4 different (disjoint) areas at once.  The standard method is lower-bounds are inclusive, upper-bounds are exclusive.

**Comment by iPollo** [comment]
Do you mean

`if(x >= MinX && x < MaxX && y >= MinY && y < MaxY)`
instead of
`if(x >= MinX && x <= MaxX && y >= MinY && y <= MaxY)`?

If so, I didn’t know it could happen, it’s interesting to know that.
