### ISSUE TITLE
Don't use bubble sort

### ISSUE THREAD

**Issue by Y-Less** [iPollo/PawnAlgorithms#3]
There's no good reason to include it, it just encourages exceptionally bad practices.

**Comment by iPollo** [comment]
Yes, I thought on that occasion, but what defines the presence of the good is the existence of evil (if this analogy makes any sense), and vice versa.

However, taking into account the reason for the repository, it would not really be "useful" to include this algorithm. Even for educational reasons.

But I believe that removing is not exactly necessary (or maybe it is and I am wrong), maybe putting a detailed description of how and why it is not a good type of code that does not use good practices it's the best choice.

So understanding what is the problem, why is it a problem and why is it not good practice, so you can really go for good practice, what do you think about?

I think I'll remove it next day.

**Comment by Y-Less** [comment]
Trust me, if you provide something, people will use it.  They won't read about why they shouldn't - people ask about how to use things even when explicitly told not to directly.
